project:
  type: website

website:
  title: "scrollytelling"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: [cosmo, brand, assets/custom_theme.scss]
    toc: true

